# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mantenimiento.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mantenimiento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13mantenimiento.proto\x12\rmantenimiento\"%\n\x11PredictionRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x01\"E\n\x12PredictionResponse\x12\x18\n\x10proba_no_failure\x18\x01 \x01(\x01\x12\x15\n\rproba_failure\x18\x02 \x01(\x01\"\x14\n\x12HealthCheckRequest\"$\n\x13HealthCheckResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x32\xbf\x01\n\x10InferenceService\x12U\n\x0ePredictFailure\x12 .mantenimiento.PredictionRequest\x1a!.mantenimiento.PredictionResponse\x12T\n\x0bHealthCheck\x12!.mantenimiento.HealthCheckRequest\x1a\".mantenimiento.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mantenimiento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=38
  _globals['_PREDICTIONREQUEST']._serialized_end=75
  _globals['_PREDICTIONRESPONSE']._serialized_start=77
  _globals['_PREDICTIONRESPONSE']._serialized_end=146
  _globals['_HEALTHCHECKREQUEST']._serialized_start=148
  _globals['_HEALTHCHECKREQUEST']._serialized_end=168
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=170
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=206
  _globals['_INFERENCESERVICE']._serialized_start=209
  _globals['_INFERENCESERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
